//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace NuvemWA.Areas.Reports {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("NuvemDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class NuvemDataSet : global::System.Data.DataSet {
        
        private dsQuotesDataTable tabledsQuotes;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public NuvemDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected NuvemDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["dsQuotes"] != null)) {
                    base.Tables.Add(new dsQuotesDataTable(ds.Tables["dsQuotes"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public dsQuotesDataTable dsQuotes {
            get {
                return this.tabledsQuotes;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            NuvemDataSet cln = ((NuvemDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["dsQuotes"] != null)) {
                    base.Tables.Add(new dsQuotesDataTable(ds.Tables["dsQuotes"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tabledsQuotes = ((dsQuotesDataTable)(base.Tables["dsQuotes"]));
            if ((initTable == true)) {
                if ((this.tabledsQuotes != null)) {
                    this.tabledsQuotes.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "NuvemDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/NuvemDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabledsQuotes = new dsQuotesDataTable();
            base.Tables.Add(this.tabledsQuotes);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializedsQuotes() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            NuvemDataSet ds = new NuvemDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void dsQuotesRowChangeEventHandler(object sender, dsQuotesRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class dsQuotesDataTable : global::System.Data.TypedTableBase<dsQuotesRow> {
            
            private global::System.Data.DataColumn columnQHeaderId;
            
            private global::System.Data.DataColumn columnQHeaderDate;
            
            private global::System.Data.DataColumn columnQHeaderReference;
            
            private global::System.Data.DataColumn columnQHeaderOC;
            
            private global::System.Data.DataColumn columnQHeaderStatusInfo;
            
            private global::System.Data.DataColumn columnQHeaderOCDate;
            
            private global::System.Data.DataColumn columnQHeaderCurrencyRate;
            
            private global::System.Data.DataColumn columnQHeaderVolumeWeight;
            
            private global::System.Data.DataColumn columnQHeaderCubicFeet;
            
            private global::System.Data.DataColumn columnCustId;
            
            private global::System.Data.DataColumn columnx_StatusName;
            
            private global::System.Data.DataColumn columnx_BrokerName;
            
            private global::System.Data.DataColumn columnx_CustName;
            
            private global::System.Data.DataColumn columnx_VendorName;
            
            private global::System.Data.DataColumn columnx_Profit;
            
            private global::System.Data.DataColumn columnx_ExchangeVariation;
            
            private global::System.Data.DataColumn columnx_DateOrderReceived;
            
            private global::System.Data.DataColumn columnx_PORate;
            
            private global::System.Data.DataColumn columnx_PBRate;
            
            private global::System.Data.DataColumn columnx_DateApproved;
            
            private global::System.Data.DataColumn columnx_ProfitPct;
            
            private global::System.Data.DataColumn columnQHeaderNumFianza;
            
            private global::System.Data.DataColumn columnx_Total;
            
            private global::System.Data.DataColumn columnx_Cost;
            
            private global::System.Data.DataColumn columnx_InternalCharges;
            
            private global::System.Data.DataColumn columnx_InvoiceBalance;
            
            private global::System.Data.DataColumn columnx_PaidDate;
            
            private global::System.Data.DataColumn columnx_DefaultOrder;
            
            private global::System.Data.DataColumn columnx_Paid;
            
            private global::System.Data.DataColumn columnPOBalance;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsQuotesDataTable() {
                this.TableName = "dsQuotes";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal dsQuotesDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected dsQuotesDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn QHeaderIdColumn {
                get {
                    return this.columnQHeaderId;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn QHeaderDateColumn {
                get {
                    return this.columnQHeaderDate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn QHeaderReferenceColumn {
                get {
                    return this.columnQHeaderReference;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn QHeaderOCColumn {
                get {
                    return this.columnQHeaderOC;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn QHeaderStatusInfoColumn {
                get {
                    return this.columnQHeaderStatusInfo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn QHeaderOCDateColumn {
                get {
                    return this.columnQHeaderOCDate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn QHeaderCurrencyRateColumn {
                get {
                    return this.columnQHeaderCurrencyRate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn QHeaderVolumeWeightColumn {
                get {
                    return this.columnQHeaderVolumeWeight;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn QHeaderCubicFeetColumn {
                get {
                    return this.columnQHeaderCubicFeet;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CustIdColumn {
                get {
                    return this.columnCustId;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn x_StatusNameColumn {
                get {
                    return this.columnx_StatusName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn x_BrokerNameColumn {
                get {
                    return this.columnx_BrokerName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn x_CustNameColumn {
                get {
                    return this.columnx_CustName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn x_VendorNameColumn {
                get {
                    return this.columnx_VendorName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn x_ProfitColumn {
                get {
                    return this.columnx_Profit;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn x_ExchangeVariationColumn {
                get {
                    return this.columnx_ExchangeVariation;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn x_DateOrderReceivedColumn {
                get {
                    return this.columnx_DateOrderReceived;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn x_PORateColumn {
                get {
                    return this.columnx_PORate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn x_PBRateColumn {
                get {
                    return this.columnx_PBRate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn x_DateApprovedColumn {
                get {
                    return this.columnx_DateApproved;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn x_ProfitPctColumn {
                get {
                    return this.columnx_ProfitPct;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn QHeaderNumFianzaColumn {
                get {
                    return this.columnQHeaderNumFianza;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn x_TotalColumn {
                get {
                    return this.columnx_Total;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn x_CostColumn {
                get {
                    return this.columnx_Cost;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn x_InternalChargesColumn {
                get {
                    return this.columnx_InternalCharges;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn x_InvoiceBalanceColumn {
                get {
                    return this.columnx_InvoiceBalance;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn x_PaidDateColumn {
                get {
                    return this.columnx_PaidDate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn x_DefaultOrderColumn {
                get {
                    return this.columnx_DefaultOrder;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn x_PaidColumn {
                get {
                    return this.columnx_Paid;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn POBalanceColumn {
                get {
                    return this.columnPOBalance;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsQuotesRow this[int index] {
                get {
                    return ((dsQuotesRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsQuotesRowChangeEventHandler dsQuotesRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsQuotesRowChangeEventHandler dsQuotesRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsQuotesRowChangeEventHandler dsQuotesRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsQuotesRowChangeEventHandler dsQuotesRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AdddsQuotesRow(dsQuotesRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsQuotesRow AdddsQuotesRow(
                        int QHeaderId, 
                        System.DateTime QHeaderDate, 
                        string QHeaderReference, 
                        string QHeaderOC, 
                        string QHeaderStatusInfo, 
                        System.DateTime QHeaderOCDate, 
                        decimal QHeaderCurrencyRate, 
                        decimal QHeaderVolumeWeight, 
                        decimal QHeaderCubicFeet, 
                        int CustId, 
                        string x_StatusName, 
                        string x_BrokerName, 
                        string x_CustName, 
                        string x_VendorName, 
                        decimal x_Profit, 
                        decimal x_ExchangeVariation, 
                        System.DateTime x_DateOrderReceived, 
                        decimal x_PORate, 
                        decimal x_PBRate, 
                        int x_DateApproved, 
                        decimal x_ProfitPct, 
                        string QHeaderNumFianza, 
                        decimal x_Total, 
                        decimal x_Cost, 
                        decimal x_InternalCharges, 
                        decimal x_InvoiceBalance, 
                        System.DateTime x_PaidDate, 
                        int x_DefaultOrder, 
                        string x_Paid, 
                        string POBalance) {
                dsQuotesRow rowdsQuotesRow = ((dsQuotesRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        QHeaderId,
                        QHeaderDate,
                        QHeaderReference,
                        QHeaderOC,
                        QHeaderStatusInfo,
                        QHeaderOCDate,
                        QHeaderCurrencyRate,
                        QHeaderVolumeWeight,
                        QHeaderCubicFeet,
                        CustId,
                        x_StatusName,
                        x_BrokerName,
                        x_CustName,
                        x_VendorName,
                        x_Profit,
                        x_ExchangeVariation,
                        x_DateOrderReceived,
                        x_PORate,
                        x_PBRate,
                        x_DateApproved,
                        x_ProfitPct,
                        QHeaderNumFianza,
                        x_Total,
                        x_Cost,
                        x_InternalCharges,
                        x_InvoiceBalance,
                        x_PaidDate,
                        x_DefaultOrder,
                        x_Paid,
                        POBalance};
                rowdsQuotesRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowdsQuotesRow);
                return rowdsQuotesRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsQuotesRow FindByQHeaderId(int QHeaderId) {
                return ((dsQuotesRow)(this.Rows.Find(new object[] {
                            QHeaderId})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                dsQuotesDataTable cln = ((dsQuotesDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new dsQuotesDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnQHeaderId = base.Columns["QHeaderId"];
                this.columnQHeaderDate = base.Columns["QHeaderDate"];
                this.columnQHeaderReference = base.Columns["QHeaderReference"];
                this.columnQHeaderOC = base.Columns["QHeaderOC"];
                this.columnQHeaderStatusInfo = base.Columns["QHeaderStatusInfo"];
                this.columnQHeaderOCDate = base.Columns["QHeaderOCDate"];
                this.columnQHeaderCurrencyRate = base.Columns["QHeaderCurrencyRate"];
                this.columnQHeaderVolumeWeight = base.Columns["QHeaderVolumeWeight"];
                this.columnQHeaderCubicFeet = base.Columns["QHeaderCubicFeet"];
                this.columnCustId = base.Columns["CustId"];
                this.columnx_StatusName = base.Columns["x_StatusName"];
                this.columnx_BrokerName = base.Columns["x_BrokerName"];
                this.columnx_CustName = base.Columns["x_CustName"];
                this.columnx_VendorName = base.Columns["x_VendorName"];
                this.columnx_Profit = base.Columns["x_Profit"];
                this.columnx_ExchangeVariation = base.Columns["x_ExchangeVariation"];
                this.columnx_DateOrderReceived = base.Columns["x_DateOrderReceived"];
                this.columnx_PORate = base.Columns["x_PORate"];
                this.columnx_PBRate = base.Columns["x_PBRate"];
                this.columnx_DateApproved = base.Columns["x_DateApproved"];
                this.columnx_ProfitPct = base.Columns["x_ProfitPct"];
                this.columnQHeaderNumFianza = base.Columns["QHeaderNumFianza"];
                this.columnx_Total = base.Columns["x_Total"];
                this.columnx_Cost = base.Columns["x_Cost"];
                this.columnx_InternalCharges = base.Columns["x_InternalCharges"];
                this.columnx_InvoiceBalance = base.Columns["x_InvoiceBalance"];
                this.columnx_PaidDate = base.Columns["x_PaidDate"];
                this.columnx_DefaultOrder = base.Columns["x_DefaultOrder"];
                this.columnx_Paid = base.Columns["x_Paid"];
                this.columnPOBalance = base.Columns["POBalance"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnQHeaderId = new global::System.Data.DataColumn("QHeaderId", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnQHeaderId);
                this.columnQHeaderDate = new global::System.Data.DataColumn("QHeaderDate", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnQHeaderDate);
                this.columnQHeaderReference = new global::System.Data.DataColumn("QHeaderReference", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnQHeaderReference);
                this.columnQHeaderOC = new global::System.Data.DataColumn("QHeaderOC", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnQHeaderOC);
                this.columnQHeaderStatusInfo = new global::System.Data.DataColumn("QHeaderStatusInfo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnQHeaderStatusInfo);
                this.columnQHeaderOCDate = new global::System.Data.DataColumn("QHeaderOCDate", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnQHeaderOCDate);
                this.columnQHeaderCurrencyRate = new global::System.Data.DataColumn("QHeaderCurrencyRate", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnQHeaderCurrencyRate);
                this.columnQHeaderVolumeWeight = new global::System.Data.DataColumn("QHeaderVolumeWeight", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnQHeaderVolumeWeight);
                this.columnQHeaderCubicFeet = new global::System.Data.DataColumn("QHeaderCubicFeet", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnQHeaderCubicFeet);
                this.columnCustId = new global::System.Data.DataColumn("CustId", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCustId);
                this.columnx_StatusName = new global::System.Data.DataColumn("x_StatusName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnx_StatusName);
                this.columnx_BrokerName = new global::System.Data.DataColumn("x_BrokerName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnx_BrokerName);
                this.columnx_CustName = new global::System.Data.DataColumn("x_CustName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnx_CustName);
                this.columnx_VendorName = new global::System.Data.DataColumn("x_VendorName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnx_VendorName);
                this.columnx_Profit = new global::System.Data.DataColumn("x_Profit", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnx_Profit);
                this.columnx_ExchangeVariation = new global::System.Data.DataColumn("x_ExchangeVariation", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnx_ExchangeVariation);
                this.columnx_DateOrderReceived = new global::System.Data.DataColumn("x_DateOrderReceived", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnx_DateOrderReceived);
                this.columnx_PORate = new global::System.Data.DataColumn("x_PORate", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnx_PORate);
                this.columnx_PBRate = new global::System.Data.DataColumn("x_PBRate", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnx_PBRate);
                this.columnx_DateApproved = new global::System.Data.DataColumn("x_DateApproved", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnx_DateApproved);
                this.columnx_ProfitPct = new global::System.Data.DataColumn("x_ProfitPct", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnx_ProfitPct);
                this.columnQHeaderNumFianza = new global::System.Data.DataColumn("QHeaderNumFianza", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnQHeaderNumFianza);
                this.columnx_Total = new global::System.Data.DataColumn("x_Total", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnx_Total);
                this.columnx_Cost = new global::System.Data.DataColumn("x_Cost", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnx_Cost);
                this.columnx_InternalCharges = new global::System.Data.DataColumn("x_InternalCharges", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnx_InternalCharges);
                this.columnx_InvoiceBalance = new global::System.Data.DataColumn("x_InvoiceBalance", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnx_InvoiceBalance);
                this.columnx_PaidDate = new global::System.Data.DataColumn("x_PaidDate", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnx_PaidDate);
                this.columnx_DefaultOrder = new global::System.Data.DataColumn("x_DefaultOrder", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnx_DefaultOrder);
                this.columnx_Paid = new global::System.Data.DataColumn("x_Paid", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnx_Paid);
                this.columnPOBalance = new global::System.Data.DataColumn("POBalance", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPOBalance);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnQHeaderId}, true));
                this.columnQHeaderId.AllowDBNull = false;
                this.columnQHeaderId.Unique = true;
                this.columnQHeaderReference.AllowDBNull = false;
                this.columnQHeaderReference.MaxLength = 50;
                this.columnQHeaderOC.MaxLength = 20;
                this.columnQHeaderStatusInfo.MaxLength = 100;
                this.columnx_StatusName.AllowDBNull = false;
                this.columnx_StatusName.MaxLength = 200;
                this.columnx_BrokerName.AllowDBNull = false;
                this.columnx_BrokerName.MaxLength = 100;
                this.columnx_CustName.AllowDBNull = false;
                this.columnx_CustName.MaxLength = 200;
                this.columnx_VendorName.MaxLength = 100;
                this.columnx_ProfitPct.ReadOnly = true;
                this.columnQHeaderNumFianza.MaxLength = 20;
                this.columnx_Total.ReadOnly = true;
                this.columnx_Cost.ReadOnly = true;
                this.columnx_InternalCharges.ReadOnly = true;
                this.columnx_InvoiceBalance.ReadOnly = true;
                this.columnx_PaidDate.ReadOnly = true;
                this.columnx_DefaultOrder.ReadOnly = true;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsQuotesRow NewdsQuotesRow() {
                return ((dsQuotesRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new dsQuotesRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(dsQuotesRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.dsQuotesRowChanged != null)) {
                    this.dsQuotesRowChanged(this, new dsQuotesRowChangeEvent(((dsQuotesRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.dsQuotesRowChanging != null)) {
                    this.dsQuotesRowChanging(this, new dsQuotesRowChangeEvent(((dsQuotesRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.dsQuotesRowDeleted != null)) {
                    this.dsQuotesRowDeleted(this, new dsQuotesRowChangeEvent(((dsQuotesRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.dsQuotesRowDeleting != null)) {
                    this.dsQuotesRowDeleting(this, new dsQuotesRowChangeEvent(((dsQuotesRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemovedsQuotesRow(dsQuotesRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                NuvemDataSet ds = new NuvemDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "dsQuotesDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class dsQuotesRow : global::System.Data.DataRow {
            
            private dsQuotesDataTable tabledsQuotes;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal dsQuotesRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabledsQuotes = ((dsQuotesDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int QHeaderId {
                get {
                    return ((int)(this[this.tabledsQuotes.QHeaderIdColumn]));
                }
                set {
                    this[this.tabledsQuotes.QHeaderIdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime QHeaderDate {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledsQuotes.QHeaderDateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'QHeaderDate\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.QHeaderDateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string QHeaderReference {
                get {
                    return ((string)(this[this.tabledsQuotes.QHeaderReferenceColumn]));
                }
                set {
                    this[this.tabledsQuotes.QHeaderReferenceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string QHeaderOC {
                get {
                    try {
                        return ((string)(this[this.tabledsQuotes.QHeaderOCColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'QHeaderOC\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.QHeaderOCColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string QHeaderStatusInfo {
                get {
                    try {
                        return ((string)(this[this.tabledsQuotes.QHeaderStatusInfoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'QHeaderStatusInfo\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.QHeaderStatusInfoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime QHeaderOCDate {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledsQuotes.QHeaderOCDateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'QHeaderOCDate\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.QHeaderOCDateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal QHeaderCurrencyRate {
                get {
                    try {
                        return ((decimal)(this[this.tabledsQuotes.QHeaderCurrencyRateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'QHeaderCurrencyRate\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.QHeaderCurrencyRateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal QHeaderVolumeWeight {
                get {
                    try {
                        return ((decimal)(this[this.tabledsQuotes.QHeaderVolumeWeightColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'QHeaderVolumeWeight\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.QHeaderVolumeWeightColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal QHeaderCubicFeet {
                get {
                    try {
                        return ((decimal)(this[this.tabledsQuotes.QHeaderCubicFeetColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'QHeaderCubicFeet\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.QHeaderCubicFeetColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int CustId {
                get {
                    try {
                        return ((int)(this[this.tabledsQuotes.CustIdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CustId\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.CustIdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string x_StatusName {
                get {
                    return ((string)(this[this.tabledsQuotes.x_StatusNameColumn]));
                }
                set {
                    this[this.tabledsQuotes.x_StatusNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string x_BrokerName {
                get {
                    return ((string)(this[this.tabledsQuotes.x_BrokerNameColumn]));
                }
                set {
                    this[this.tabledsQuotes.x_BrokerNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string x_CustName {
                get {
                    return ((string)(this[this.tabledsQuotes.x_CustNameColumn]));
                }
                set {
                    this[this.tabledsQuotes.x_CustNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string x_VendorName {
                get {
                    try {
                        return ((string)(this[this.tabledsQuotes.x_VendorNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'x_VendorName\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.x_VendorNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal x_Profit {
                get {
                    try {
                        return ((decimal)(this[this.tabledsQuotes.x_ProfitColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'x_Profit\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.x_ProfitColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal x_ExchangeVariation {
                get {
                    try {
                        return ((decimal)(this[this.tabledsQuotes.x_ExchangeVariationColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'x_ExchangeVariation\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.x_ExchangeVariationColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime x_DateOrderReceived {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledsQuotes.x_DateOrderReceivedColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'x_DateOrderReceived\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.x_DateOrderReceivedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal x_PORate {
                get {
                    try {
                        return ((decimal)(this[this.tabledsQuotes.x_PORateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'x_PORate\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.x_PORateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal x_PBRate {
                get {
                    try {
                        return ((decimal)(this[this.tabledsQuotes.x_PBRateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'x_PBRate\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.x_PBRateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int x_DateApproved {
                get {
                    try {
                        return ((int)(this[this.tabledsQuotes.x_DateApprovedColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'x_DateApproved\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.x_DateApprovedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal x_ProfitPct {
                get {
                    try {
                        return ((decimal)(this[this.tabledsQuotes.x_ProfitPctColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'x_ProfitPct\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.x_ProfitPctColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string QHeaderNumFianza {
                get {
                    try {
                        return ((string)(this[this.tabledsQuotes.QHeaderNumFianzaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'QHeaderNumFianza\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.QHeaderNumFianzaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal x_Total {
                get {
                    try {
                        return ((decimal)(this[this.tabledsQuotes.x_TotalColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'x_Total\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.x_TotalColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal x_Cost {
                get {
                    try {
                        return ((decimal)(this[this.tabledsQuotes.x_CostColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'x_Cost\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.x_CostColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal x_InternalCharges {
                get {
                    try {
                        return ((decimal)(this[this.tabledsQuotes.x_InternalChargesColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'x_InternalCharges\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.x_InternalChargesColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal x_InvoiceBalance {
                get {
                    try {
                        return ((decimal)(this[this.tabledsQuotes.x_InvoiceBalanceColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'x_InvoiceBalance\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.x_InvoiceBalanceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime x_PaidDate {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledsQuotes.x_PaidDateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'x_PaidDate\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.x_PaidDateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int x_DefaultOrder {
                get {
                    try {
                        return ((int)(this[this.tabledsQuotes.x_DefaultOrderColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'x_DefaultOrder\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.x_DefaultOrderColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string x_Paid {
                get {
                    try {
                        return ((string)(this[this.tabledsQuotes.x_PaidColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'x_Paid\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.x_PaidColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string POBalance {
                get {
                    try {
                        return ((string)(this[this.tabledsQuotes.POBalanceColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'POBalance\' in table \'dsQuotes\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsQuotes.POBalanceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsQHeaderDateNull() {
                return this.IsNull(this.tabledsQuotes.QHeaderDateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetQHeaderDateNull() {
                this[this.tabledsQuotes.QHeaderDateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsQHeaderOCNull() {
                return this.IsNull(this.tabledsQuotes.QHeaderOCColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetQHeaderOCNull() {
                this[this.tabledsQuotes.QHeaderOCColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsQHeaderStatusInfoNull() {
                return this.IsNull(this.tabledsQuotes.QHeaderStatusInfoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetQHeaderStatusInfoNull() {
                this[this.tabledsQuotes.QHeaderStatusInfoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsQHeaderOCDateNull() {
                return this.IsNull(this.tabledsQuotes.QHeaderOCDateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetQHeaderOCDateNull() {
                this[this.tabledsQuotes.QHeaderOCDateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsQHeaderCurrencyRateNull() {
                return this.IsNull(this.tabledsQuotes.QHeaderCurrencyRateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetQHeaderCurrencyRateNull() {
                this[this.tabledsQuotes.QHeaderCurrencyRateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsQHeaderVolumeWeightNull() {
                return this.IsNull(this.tabledsQuotes.QHeaderVolumeWeightColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetQHeaderVolumeWeightNull() {
                this[this.tabledsQuotes.QHeaderVolumeWeightColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsQHeaderCubicFeetNull() {
                return this.IsNull(this.tabledsQuotes.QHeaderCubicFeetColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetQHeaderCubicFeetNull() {
                this[this.tabledsQuotes.QHeaderCubicFeetColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCustIdNull() {
                return this.IsNull(this.tabledsQuotes.CustIdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCustIdNull() {
                this[this.tabledsQuotes.CustIdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isx_VendorNameNull() {
                return this.IsNull(this.tabledsQuotes.x_VendorNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setx_VendorNameNull() {
                this[this.tabledsQuotes.x_VendorNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isx_ProfitNull() {
                return this.IsNull(this.tabledsQuotes.x_ProfitColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setx_ProfitNull() {
                this[this.tabledsQuotes.x_ProfitColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isx_ExchangeVariationNull() {
                return this.IsNull(this.tabledsQuotes.x_ExchangeVariationColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setx_ExchangeVariationNull() {
                this[this.tabledsQuotes.x_ExchangeVariationColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isx_DateOrderReceivedNull() {
                return this.IsNull(this.tabledsQuotes.x_DateOrderReceivedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setx_DateOrderReceivedNull() {
                this[this.tabledsQuotes.x_DateOrderReceivedColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isx_PORateNull() {
                return this.IsNull(this.tabledsQuotes.x_PORateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setx_PORateNull() {
                this[this.tabledsQuotes.x_PORateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isx_PBRateNull() {
                return this.IsNull(this.tabledsQuotes.x_PBRateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setx_PBRateNull() {
                this[this.tabledsQuotes.x_PBRateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isx_DateApprovedNull() {
                return this.IsNull(this.tabledsQuotes.x_DateApprovedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setx_DateApprovedNull() {
                this[this.tabledsQuotes.x_DateApprovedColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isx_ProfitPctNull() {
                return this.IsNull(this.tabledsQuotes.x_ProfitPctColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setx_ProfitPctNull() {
                this[this.tabledsQuotes.x_ProfitPctColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsQHeaderNumFianzaNull() {
                return this.IsNull(this.tabledsQuotes.QHeaderNumFianzaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetQHeaderNumFianzaNull() {
                this[this.tabledsQuotes.QHeaderNumFianzaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isx_TotalNull() {
                return this.IsNull(this.tabledsQuotes.x_TotalColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setx_TotalNull() {
                this[this.tabledsQuotes.x_TotalColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isx_CostNull() {
                return this.IsNull(this.tabledsQuotes.x_CostColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setx_CostNull() {
                this[this.tabledsQuotes.x_CostColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isx_InternalChargesNull() {
                return this.IsNull(this.tabledsQuotes.x_InternalChargesColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setx_InternalChargesNull() {
                this[this.tabledsQuotes.x_InternalChargesColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isx_InvoiceBalanceNull() {
                return this.IsNull(this.tabledsQuotes.x_InvoiceBalanceColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setx_InvoiceBalanceNull() {
                this[this.tabledsQuotes.x_InvoiceBalanceColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isx_PaidDateNull() {
                return this.IsNull(this.tabledsQuotes.x_PaidDateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setx_PaidDateNull() {
                this[this.tabledsQuotes.x_PaidDateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isx_DefaultOrderNull() {
                return this.IsNull(this.tabledsQuotes.x_DefaultOrderColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setx_DefaultOrderNull() {
                this[this.tabledsQuotes.x_DefaultOrderColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isx_PaidNull() {
                return this.IsNull(this.tabledsQuotes.x_PaidColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setx_PaidNull() {
                this[this.tabledsQuotes.x_PaidColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPOBalanceNull() {
                return this.IsNull(this.tabledsQuotes.POBalanceColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPOBalanceNull() {
                this[this.tabledsQuotes.POBalanceColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class dsQuotesRowChangeEvent : global::System.EventArgs {
            
            private dsQuotesRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsQuotesRowChangeEvent(dsQuotesRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsQuotesRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591